export type ServerStatus = 'running' | 'stopped' | 'maintenance';
export type ServerLocation = 'DC-East' | 'DC-West' | 'DC-Europe';

export interface Server {
    id: string;
    hostname: string;
    ipAddress: string;
    status: ServerStatus;
    location: ServerLocation;
    os: string;
    cpuCores: number;
    ramGb: number;
    storageGb: number;
    uptimeHours: number;
}

export const MOCK_SERVERS: Server[] = [
    {
        id: 'srv-001',
        hostname: 'web-prod-01',
        ipAddress: '10.0.1.10',
        status: 'running',
        location: 'DC-East',
        os: 'Ubuntu 22.04 LTS',
        cpuCores: 16,
        ramGb: 64,
        storageGb: 500,
        uptimeHours: 2184,
    },
    {
        id: 'srv-002',
        hostname: 'web-prod-02',
        ipAddress: '10.0.1.11',
        status: 'running',
        location: 'DC-East',
        os: 'Ubuntu 22.04 LTS',
        cpuCores: 16,
        ramGb: 64,
        storageGb: 500,
        uptimeHours: 2184,
    },
    {
        id: 'srv-003',
        hostname: 'db-master-01',
        ipAddress: '10.0.2.20',
        status: 'running',
        location: 'DC-West',
        os: 'Red Hat Enterprise Linux 9',
        cpuCores: 32,
        ramGb: 128,
        storageGb: 2000,
        uptimeHours: 4320,
    },
    {
        id: 'srv-004',
        hostname: 'db-replica-01',
        ipAddress: '10.0.2.21',
        status: 'maintenance',
        location: 'DC-West',
        os: 'Red Hat Enterprise Linux 9',
        cpuCores: 32,
        ramGb: 128,
        storageGb: 2000,
        uptimeHours: 0,
    },
    {
        id: 'srv-005',
        hostname: 'cache-node-01',
        ipAddress: '10.0.3.30',
        status: 'running',
        location: 'DC-East',
        os: 'Debian 12',
        cpuCores: 8,
        ramGb: 32,
        storageGb: 100,
        uptimeHours: 720,
    },
    {
        id: 'srv-006',
        hostname: 'storage-nas-01',
        ipAddress: '10.0.4.40',
        status: 'running',
        location: 'DC-Europe',
        os: 'TrueNAS SCALE',
        cpuCores: 12,
        ramGb: 64,
        storageGb: 24000,
        uptimeHours: 8760,
    },
    {
        id: 'srv-007',
        hostname: 'monitor-01',
        ipAddress: '10.0.5.50',
        status: 'running',
        location: 'DC-Europe',
        os: 'Ubuntu 22.04 LTS',
        cpuCores: 4,
        ramGb: 16,
        storageGb: 250,
        uptimeHours: 1440,
    },
    {
        id: 'srv-008',
        hostname: 'backup-srv-01',
        ipAddress: '10.0.6.60',
        status: 'stopped',
        location: 'DC-West',
        os: 'Windows Server 2022',
        cpuCores: 8,
        ramGb: 32,
        storageGb: 8000,
        uptimeHours: 0,
    },
    {
        id: 'srv-009',
        hostname: 'ci-runner-01',
        ipAddress: '10.0.7.70',
        status: 'running',
        location: 'DC-East',
        os: 'Ubuntu 24.04 LTS',
        cpuCores: 16,
        ramGb: 32,
        storageGb: 500,
        uptimeHours: 336,
    },
    {
        id: 'srv-010',
        hostname: 'gateway-eu-01',
        ipAddress: '10.0.8.80',
        status: 'maintenance',
        location: 'DC-Europe',
        os: 'Alpine Linux 3.19',
        cpuCores: 4,
        ramGb: 8,
        storageGb: 50,
        uptimeHours: 0,
    },
    {
        id: 'srv-011',
        hostname: 'ml-gpu-01',
        ipAddress: '10.0.9.90',
        status: 'running',
        location: 'DC-West',
        os: 'Ubuntu 22.04 LTS',
        cpuCores: 64,
        ramGb: 256,
        storageGb: 4000,
        uptimeHours: 168,
    },
    {
        id: 'srv-012',
        hostname: 'dns-primary',
        ipAddress: '10.0.10.10',
        status: 'running',
        location: 'DC-East',
        os: 'Debian 12',
        cpuCores: 2,
        ramGb: 4,
        storageGb: 50,
        uptimeHours: 17520,
    },
];
